### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by danmt** [JMTeixeira17/first-challenge#1]
Tu proyecto está casi listo, me parecio interesante que agregaras el primer challenge en una carpeta. Cual es tu plan? Hacer cada reto en un repo separado?

Al correrlo con `nx serve` da un error de process, el ejemplo de polyfills tiene un error. Para arreglarlo, reemplaza el contenido de [los polyfills](https://github.com/JMTeixeira17/first-challenge/blob/main/first-challenge/src/polyfills.ts) con este codigo:

```typescript
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { }};  
```

**Comment by JMTeixeira17** [comment]
Sí, quisiera separar todo en partes para no perderme. Aunque capaz agarro y termino usando un mismo repo jeje. Gracias!

**Comment by danmt** [comment]
Buenisimo, yo la semana que viene les voy a dar un par de recomendaciones como para que se familiaricen mas con GitHub, como usar Pull Requests, manejarnos con branches, etc... Saludos y felicidades de nuevo por la graduacion!!
